#!/bin/sh

# autologin for live
sed -i -e 's|#AutoLoginEnable=true|AutoLoginEnable=true|' /etc/kde3/kdm/kdmrc
sed -i -e 's|#AutoLoginAgain=true|AutoLoginAgain=true|' /etc/kde3/kdm/kdmrc
sed -i -e 's|#AutoLoginUser=fred|AutoLoginUser=lumpia|' /etc/kde3/kdm/kdmrc

# set crystalkuliax to default.kde
rm /usr/share/icons/default.kde
ln -s /usr/share/icons/crystalkuliax /usr/share/icons/default.kde

# kde config skeleton for users
mkdir -p /etc/skel/.kde/share/config
cp -a /usr/share/kuliax-artwork/kde-profile/share/config/* /etc/skel/.kde/share/config/

# remove mplayer.desktop
rm /usr/share/applications/mplayer.desktop

#-fix mimelnk
# autoembed false for opening pdf files
sed -i -e 's|X-KDE-AutoEmbed=true|X-KDE-AutoEmbed=false|' /usr/share/mimelnk/application/pdf.desktop

# presentation
OFFP=`grep -r Icon=presentation /usr/share/mimelnk/*| sed '/magicpoint.desktop/d' | cut -d":" -f1`
for ODP in $OFFP
do
	sed -i -e 's|Icon=presentation|Icon=openofficeorg3-oasis-presentation|' $ODP
done

# fix adduser.conf
sed -i -e 's|#EXTRA_GROUPS="dialout cdrom floppy audio video plugdev users games"\
|EXTRA_GROUPS="dialout cdrom floppy audio video plugdev netdev powerdev users"|' /etc/adduser.conf
sed -i -e 's|#ADD_EXTRA_GROUPS=1|ADD_EXTRA_GROUPS=1|' /etc/adduser.conf
