#!/bin/sh

set -e

log () {
	logger -t kuliax_late_cmd "$@"
}

log "Setting up GRUB splash for Kuliax"
sed -i -e 's|AutoLoginEnable=true|#AutoLoginEnable=true|' /target/etc/kde3/kdm/kdmrc
sed -i -e 's|//grub/splash.xpm.gz|/boot/grub/splash.xpm.gz|' /target/boot/grub/menu.lst
sed -i -e 's|"Debian GNU/Linux, kernel 2.6.30-kuliax.2-686"|"Kuliax 7.0, kernel 2.6.30-kuliax.2-686"|g' /target/boot/grub/menu.lst

log "Copying sources.list"
cp /cdrom/install/sources.list /target/etc/apt/

log "Flushing filesystem buffers"
sync
