#!/bin/sh

set -e

log ()
{
	logger -t kuliax_late_cmd "$@"
}

log "Fixing GRUB splash and setting up suspend for Kuliax"
SWP=`cat /target/etc/fstab | tr -s ' ' | sed '/swap/!d' | cut -d" " -f1`
sed -i -e "s|quite splash|splash resume=${SWP}|g" /target/boot/grub/menu.lst

BOOT=`df -h | tr -s ' ' | sed '/boot/!d' | cut -d" " -f6`
if [ "${BOOT}" = "/target/boot" ]; then
	continue
else
	sed -i -e 's|//grub/splash.xpm.gz|/boot/grub/splash.xpm.gz|' /target/boot/grub/menu.lst
fi

log "Copying sources.list"
cp /cdrom/install/sources.list /target/etc/apt/

log "Removing KDE autologin"
sed -i -e "s|AutoLoginEnable=true|#AutoLoginEnable=true|" /target/etc/kde3/kdm/kdmrc

log "Removing sudo as default in KDE"
rm /target/usr/share/kuliax-artwork/kde-profile/share/config/kdesurc

log "Copying GTK profile for root"
cp /target/etc/skel/.gtkrc-2.0-kde /target/root/
echo "export GTK2_RC_FILES=$HOME/.gtkrc-2.0-kde" >> /target/root/.profile

log "Activating rsyslog on boot"
in-target update-rc.d rsyslog defaults

log "Removing squashfs-tools"
in-target apt-get remove --purge -y squashfs-tools

log "Flushing filesystem buffers"
sync
