0fPREREQUISITES FOR USING KULIAX07                                                09F207

You must have x86 800 MHz processor with at least 128 megabytes of RAM
to run Kuliax Live system and/or to install it in your hard drive with 
Kuliax installer.

Read documentation which is available at Kuliax Project website,
0fhttp:/kuliax.org/07 for more information.


If you want to install Kuliax, you should have space on your hard drive 
to create a new disk partition of at least 2500 megabytes.

You'll need more disk space to install additional packages, depending on 
what you wish to do with your new Kuliax system.

Thank you for choosing Kuliax!





Press F1control and F then 1 for the help index, or ENTER to 
