0fGETTING HELP07                                                                  09F907

If you can't run Kuliax Live system or install Kuliax, don't despair!
The Kuliax team is ready to help you! We are especially interested in
hearing about installation problems, because in general they don't
happen to only 0fone07 person.

We've either already heard about your particular problem and can dispense a
quick fix, or we would like to hear about it and work through it with you,
and the next user who comes up with the same problem will profit from your
experience!

See the Installation Quickstart for more information, which is available
at the Kuliax website, 0fhttp:/kuliax.org/07, or join our Mailing List
0fkuliax@googlegroups.com07 to discuss all related issues with Kuliax,
Debian, or Free Software in general.





Press F1control and F then 1 for the help index, or ENTER to 
